spring.datasource.url=jdbc:h2:mem:stajflo
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.jpa.hibernate.ddl-auto=update
jwt.secret=QUlERkFUbGlrYjR0WGlxNmNldXh0ZE53eGd1anN2N3hXekZ4c0Z0bGFnNWhqQ0Fqcm00V05FTHBvV1Jrc3h1cQ==
jwt.expiration=86400000
spring.jpa.open-in-view=false
logging.level.org.springframework.security=DEBUG